- name: Create EC2 instance
  local_action:
    module: ec2
    key_name: "seq-master"
    group: "bootstrap-test"
    instance_type: "m3.large"
    image: "ami-4b20c70f"
    wait: yes
    region: "us-west-1"
    count: 3
    id: "bootstrap-test-5"
    volumes:
      - device_name: /dev/xvda
        volume_size: 30
        delete_on_termination: true
  register: ec2result

- name: Add name tag to launched instance
  ec2_tag: region=us-west-1 resource={{ item.id }} state=present
  with_items: ec2result.instances
  args:
    tags:
      Name: "bootstrap-test-5"

- name: Wait for SSH to come up
  local_action: wait_for host={{ item.public_ip }} port=22 delay=1 timeout=600 state=started
  with_items: ec2result.instances

- name: Create or empty node descriptor file
  shell: bash -c '> /playbook/ips'

- name: Create local node descriptor file
  shell: echo "{{ item.private_ip }}:2376" >> /playbook/ips
  with_items: ec2result.instances

- name: add hosts to inventory
  add_host: name={{ item.public_ip }} groups=ec2nodes
  with_items: ec2result.instances

- name: Generate server keys + certificates
  shell: cd keys &&  openssl genrsa -out server-key-{{ item.private_ip }}.pem 2049 && openssl req -subj "/CN={{ item.private_ip }}" -new -key server-key-{{ item.private_ip }}.pem -out server-{{ item.private_ip }}.csr && echo subjectAltName = IP:127.0.0.1,IP:{{ item.private_ip }},IP:{{ item.public_ip }} > extfile-{{ item.private_ip }}.cnf && echo "extendedKeyUsage = clientAuth,serverAuth" >> extfile-{{ item.private_ip }}.cnf && openssl x509 -req -days 365 -in server-{{ item.private_ip }}.csr -CA /playbook/keys/ca.pem -CAkey /playbook/keys/ca-key.pem -CAcreateserial -out server-cert-{{ item.private_ip }}.pem -extfile extfile-{{ item.private_ip }}.cnf
  with_items: ec2result.instances

- name: Delete temp files
  shell: rm /playbook/keys/extfile* && rm /playbook/keys/server*.csr
